In [2]:
import pandas as pd

In [8]:
data = pd.read_csv("netflix1.csv")

In [10]:
data.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8790 non-null   object
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   object
 8   duration      8790 non-null   object
 9   listed_in     8790 non-null   object
dtypes: int64(1), object(9)
memory usage: 686.8+ KB

In [13]:
""""

*********************************
steps to clean the data

1) deleting redundant columns 
2) renameing the columns 
3) droping the duplicates 
4) remove the NAN values from the dataset 
5) check for some more transformations

*********************************


"""

'"\n\n*********************************\nsteps to clean the data\n\n1) deleting redundant columns \n2) renameing the columns \n3) droping the duplicates \n4) remove the NAN values from the dataset \n5) check for some more transformations\n\n*********************************\n\n\n'

In [14]:
data.head(1)

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries

In [15]:
data.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in'],
      dtype='object')

In [16]:
data[["rating"]]

     rating
0     PG-13
1     TV-MA
2     TV-MA
3     TV-PG
4     TV-MA
...     ...
8785  TV-PG
8786  TV-Y7
8787  TV-PG
8788   TV-Y
8789  TV-Y7

[8790 rows x 1 columns]

In [19]:
data.drop(columns="rating" , inplace=True)

In [20]:
data.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'duration', 'listed_in'],
      dtype='object')

In [24]:
new_columns_names = []

for i in data.columns :
    new_columns_names.append(i.capitalize())

In [25]:
new_columns_names

['Show_id',
 'Type',
 'Title',
 'Director',
 'Country',
 'Date_added',
 'Release_year',
 'Duration',
 'Listed_in']

In [26]:
data.columns = new_columns_names

In [30]:
data.head()

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Duration,Listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,125 min,"Dramas, Independent Movies, International Movies"

In [35]:
data.duplicated().sum()

np.int64(0)

In [36]:
# for clean duplicates 
# data.drop_duplicates(inplace=True)

In [38]:
data.isna().sum().sum()

np.int64(0)

In [39]:
# if we want to remove the NAN values from the dataset we can use the below code
# data.dropna(inplace=True)

In [ ]:
data["Show_id"].unique()
# we need to transform the show_id column to be a string type instead of int type because it is an id and we don't need to do any calculations on it

array(['s1', 's3', 's6', ..., 's8801', 's8784', 's8786'],
      shape=(8790,), dtype=object)

In [43]:
data["Show_id"] = data["Show_id"].apply(lambda x : x.split("s")[1])

In [44]:
data

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Duration,Listed_in
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,90 min,Documentaries
1,3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,91 min,"Children & Family Movies, Comedies"
4,8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...
8785,8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,2 Seasons,"International TV Shows, TV Dramas"
8786,8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,3 Seasons,Kids' TV
8787,8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,1 Season,Kids' TV
8789,8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,1 Season,Kids' TV

In [48]:
type(data["Show_id"][0])

str

In [50]:
data["Show_id"] = data["Show_id"].astype(int)

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Show_id       8790 non-null   int64
 1   Type          8790 non-null   object
 2   Title         8790 non-null   object
 3   Director      8790 non-null   object
 4   Country       8790 non-null   object
 5   Date_added    8790 non-null   object
 6   Release_year  8790 non-null   int64
 7   Duration      8790 non-null   object
 8   Listed_in     8790 non-null   object
dtypes: int64(2), object(7)
memory usage: 618.2+ KB

In [55]:
data["Date_added"] = data["Date_added"].apply(lambda x : x.replace("/","-"))

In [56]:
data

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Duration,Listed_in
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9-25-2021,2020,90 min,Documentaries
1,3,TV Show,Ganglands,Julien Leclercq,France,9-24-2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,9-24-2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9-22-2021,2021,91 min,"Children & Family Movies, Comedies"
4,8,Movie,Sankofa,Haile Gerima,United States,9-24-2021,1993,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...
8785,8797,TV Show,Yunus Emre,Not Given,Turkey,1-17-2017,2016,2 Seasons,"International TV Shows, TV Dramas"
8786,8798,TV Show,Zak Storm,Not Given,United States,9-13-2018,2016,3 Seasons,Kids' TV
8787,8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12-15-2016,2012,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,8784,TV Show,Yoko,Not Given,Pakistan,6-23-2018,2016,1 Season,Kids' TV
8789,8786,TV Show,YOM,Not Given,Pakistan,6-7-2018,2016,1 Season,Kids' TV

In [ ]:
data["Country"].value_counts()

Country
United States     3240
India             1057
United Kingdom     638
Pakistan           421
Not Given          287
                  ...
Luxembourg           1
Senegal              1
Belarus              1
Puerto Rico          1
Cyprus               1
Name: count, Length: 86, dtype: int64

In [64]:
df = data["Country"].value_counts().reset_index()
df[df["Country"]=="Turkey"]

   Country  count
13  Turkey    112

In [65]:
data.to_csv("netflix_cleaned.csv" , index=False)